name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        usesThe failure is due to the use of a deprecated version of `actions/upload-pages-artifact@v2`. 

To resolve this: actions/checkout@v3

      - name: Configure Pages issue, update the workflow file to use the latest version
        uses: actions/configure-pages@v4

      - of the action:

```yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy name: Upload Pages artifact
        uses: actions/upload static content to Pages

on:
  # Runs on pushes targeting the-pages-artifact@v2
        with:
          path: default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the './path/to/static/content'

      - name: Deploy to GitHub Pages Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in
        uses: actions/deploy-pages-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Updated action version
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
       @v3
